<template>
  <div>
    <p>    [ wagons光速超跑wagons光速超跑天津行情]  编者从进口现代汽车天津森龙4S店了解到，进口现代4S店，推出贷款购车优惠活动，凡在到店贷款购买进口现代劳恩斯-酷派，均可获“免息”贷款支持（0利息、0手续费）。具体形式如下表：</p><p align="center"></p><table style="TEXT-ALIGN: center; BORDER-COLLAPSE: collapse; FONT-SIZE: 13px" id="_DevelopTable" border="1" cellspacing="0" bordercolor="#000000" cellpadding="0" width="500" align="center"><tbody><tr height="35"><td style="FONT-WEIGHT: bold" bgcolor="#d6ebff" width="500" colspan="4" isshow="false">劳恩斯-酷派车型最新价格变化报价</td></tr><tr height="35"><td style="FONT-WEIGHT: bold" width="124" isshow="false">车型</td><td style="FONT-WEIGHT: bold" width="124" isshow="false">指导价<br>(万元)</td><td style="FONT-WEIGHT: bold" width="124" isshow="false">优惠形式</td><td style="FONT-WEIGHT: bold" width="124" isshow="false">现车情况</td></tr><tr height="35"><td width="124" isshow="false">2.0T 酷动<br>手动版</td><td width="124" isshow="false">19.90</td><td width="124" isshow="false">贷款免息</td><td width="124" isshow="false">少量现车</td></tr><tr><td height="35" width="124" isshow="false">2.0T 靓雅<br>自动版</td><td height="35" width="124" isshow="false">22.70</td><td height="35" width="124" isshow="false">贷款免息</td><td height="35" width="124" isshow="false">少量现车</td></tr><tr><td height="35" width="124" isshow="false">2.0T 豪华<br>自动版</td><td height="35" width="124" isshow="false">25.00</td><td height="35" width="124" isshow="false">贷款免息</td><td height="35" width="124" isshow="false">少量现车</td></tr><tr><td height="35" width="124" isshow="false">3.8L 豪华<br>手动版</td><td height="35" width="124" isshow="false">30.90</td><td height="35" width="124" isshow="false">贷款免息</td><td height="35" width="124" isshow="false">少量现车</td></tr><tr><td height="35" width="124" isshow="false">3.8L 旗舰<br>自动版</td><td height="35" width="124" isshow="false">32.50</td><td height="35" width="124" isshow="false">贷款免息</td><td height="35" width="124" isshow="false">少量现车</td></tr><tr height="35"><td width="500" colspan="4" isshow="false">信贷银行：深发展银行<br><br>免息形式：A、贷款18个月：首付三成，享受“0利息、0手续费”优惠；<br><br>          B、贷款36个月：首付三成，享受“首年0利息、0手续费”优惠。</td></tr><tr height="35"><td style="FONT-WEIGHT: bold" id="DevelopTableParentYear" width="500" colspan="4" isshow="false">2010年07月09日行情 车辆价格随时变动，敬请关注当地市场</td></tr></tbody></table><p></p><p align="center"><img alt="现代 现代(进口) 劳恩斯-酷派 09款 2.0T 靓雅自动版" src="/Image/2010072504230812647.jpg"></p><p align="center">『劳恩斯-酷派 09款 2.0T 靓雅自动版』</p><p>    劳恩斯-酷派整车享受五年或10万公里质保，首次保养免费，日常保养周期为5000公里。常规保养（如更换机油机滤等）加工时、材料费的价格在300-400元左右，大保养根据车况而定.作为一款进口跑车，劳恩斯-酷派的保养费用还是不算贵。具体请以店内报价为准。

</p>
  </div>
</template>
<script>
  export default{
    name:'1'
  }
</script>
<style></style>
